[[docs]]
  name = "Contributing"
  weight = 0
  identifier = "contributing"
  url = "/docs/contributing/"

[[docs]]
  name = "Self-Hosting"
  weight = 3
  identifier = "self-hosting"
  url = "/docs/self-hosting/"

[[docs]]
  name = "Configuration"
  weight = 2
  identifier = "configuration"
  url = "/docs/configuration/"

[[docs]]
  name = "Dekart Cloud"
  weight = 3
  identifier = "cloud"
  url = "/docs/cloud/"

[[docs]]
  name = "Snowpark"
  weight = 1
  identifier = "snowflake-snowpark"
  url = "/docs/snowflake-snowpark/"

[[docs]]
  name = "About"
  weight = 1
  identifier = "about"
  url = "/docs/about/"

[[docs]]
  name = "Map Examples"
  weight = 1
  identifier = "examples"
  url = "/docs/about/"


[[main]]
  name = "Login"
  url = "https://cloud.dekart.xyz/"
  weight = 6

[[main]]
  name = "Pricing"
  url = "/cloud"
  weight = 7

[[main]]
  name = "Playground"
  url = "/docs/about/playground/"
  weight = 8

[[main]]
  name = "Docs"
  url = "/docs/"
  weight = 9

[[main]]
  name = "GitHub"
  url = "https://github.com/dekart-xyz/dekart"
  weight = 15

[[main]]
  name = "Slack"
  url = "https://slack.dekart.xyz"
  weight = 15

#[[main]]
#  name = "Blog"
#  url = "/blog/"
#  weight = 20

#[[main]]
#  name = "Contribute ðŸ’œ"
#  url = "/support-project"
#  weight = 21

# [[social]]
#   name = "Twitter"
#   pre = "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"20\" height=\"20\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\" class=\"feather feather-twitter\"><path d=\"M23 3a10.9 10.9 0 0 1-3.14 1.53 4.48 4.48 0 0 0-7.86 3v1A10.66 10.66 0 0 1 3 4s-4 9 5 13a11.64 11.64 0 0 1-7 2c9 5 20 0 20-11.5a4.5 4.5 0 0 0-.08-.83A7.72 7.72 0 0 0 23 3z\"></path></svg>"
#   url = "https://twitter.com/gethyas"
#   weight = 10

[[social]]
  name = "GitHub"
  pre = '<svg width="24" height="24" viewBox="0 0 1024 1024" fill="none" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" clip-rule="evenodd" d="M512 0C229.12 0 0 229.12 0 512c0 226.56 146.56 417.92 350.08 485.76 25.6 4.48 35.2-10.88 35.2-24.32 0-12.16-.64-52.48-.64-95.36-128.64 23.68-161.92-31.36-172.16-60.16-5.76-14.72-30.72-60.16-52.48-72.32-17.92-9.6-43.52-33.28-.64-33.92 40.32-.64 69.12 37.12 78.72 52.48 46.08 77.44 119.68 55.68 149.12 42.24 4.48-33.28 17.92-55.68 32.64-68.48-113.92-12.8-232.96-56.96-232.96-252.8 0-55.68 19.84-101.76 52.48-137.6-5.12-12.8-23.04-65.28 5.12-135.68 0 0 42.88-13.44 140.8 52.48 40.96-11.52 84.48-17.28 128-17.28 43.52 0 87.04 5.76 128 17.28 97.92-66.56 140.8-52.48 140.8-52.48 28.16 70.4 10.24 122.88 5.12 135.68 32.64 35.84 52.48 81.28 52.48 137.6 0 196.48-119.68 240-233.6 252.8 18.56 16 34.56 46.72 34.56 94.72 0 68.48-.64 123.52-.64 140.8 0 13.44 9.6 29.44 35.2 24.32C877.44 929.92 1024 737.92 1024 512 1024 229.12 794.88 0 512 0z" fill="#1B1F23"/></svg>'
  url = "http://github.com/dekart-xyz/dekart"
  weight = 20

# [[footer]]
#   name = "Legal"
#   url = "/legal/"
#   weight = 15
[[footer]]
  name = "Behind the scenes in Slack group"
  url = "https://slack.dekart.xyz"
  weight = 10
