# Meta Data for SEO

## Homepage
title = "Dekart"
titleSeparator = "-"
titleAddition = "Geospatial analysis for BigQuery"
description = "Dekart is an open-source data visualization and analytical tool for large scale geo-spatial data."

## Open Graph + Twitter Cards
images = ["dekart-social-preview.png"]
twitterCreator = "delfrrr"
ogLocale = "en_US"

## JSON-LD
# schemaType = "Organization"
schemaLogo = "dekart-logo.png"
# schemaTwitter = "http://twitter.com/delfrrr"
# schemaLinkedIn = "https://www.linkedin.com/in/bilonenko/"
schemaGitHub = "https://github.com/dekart-xyz/dekart"
schemaSection = "blog"

## Sitelinks Search Box
siteLinksSearchBox = false

## Chrome Browser
themeColor = "#fff"

# Images
quality = 100
bgColor = "#fff"
landscapePhotoWidths = [1800, 900, 800, 700, 600]
portraitPhotoWidths = [1600, 800, 700, 600]
lqipWidth = "20x"

# Footer
# footer = "Powered by <a href=\"https://www.netlify.com/\">Netlify</a>, <a href=\"https://gohugo.io/\">Hugo</a>, and <a href=\"https://getdoks.org/\">Doks</a>"
footer = "Like Dekart? <a href=\"https://github.com/dekart-xyz/dekart/\">Give it ⭐️on GitHub!</a>"

# Alert
alert = false
alertText = "Like Dekart? <a class=\"alert-link\" href=\"https://github.com/dekart-xyz/dekart/stargazers\">Give it a Star!</a></a>"

# Edit Page
docsRepo = "https://github.com/dekart-xyz/www"
editPage = true
